version: '3.1'

services:
  mongo:
    container_name: mongo
    image: mongo:5.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: example
    ports:
      - 27017:27017
    volumes:
      - ./mock/mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d